name: emvia
description: 'Emvia, a simple relaxing game to unwind and find your inner peace.'
publish_to: 'none'

version: 1.0.0+1

environment:
    sdk: ^3.10.7

dependencies:
    flutter:
        sdk: flutter

    flame: ^1.34.0
    flame_audio: ^2.11.12
    google_fonts: ^7.0.2
    cupertino_icons: ^1.0.8
    flutter_localizations:
        sdk: flutter
    intl: 0.20.2
    shared_preferences: ^2.5.4
    http: ^1.2.0
    flutter_launcher_icons: ^0.14.4
    path_provider: ^2.1.5
    open_filex: ^4.7.0
    # device_preview: ^1.3.1

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^6.0.0

flutter:
    generate: true
    uses-material-design: true

    assets:
        - assets/images/
        - assets/images/main-menu/
        - assets/images/stress/
        - assets/images/stress/stress-scene/
        - assets/images/player/
        - assets/images/player/olya/
        - assets/images/player/liam/
        - assets/images/backpack/
        - assets/images/player-selecting/
        - assets/images/scenes/
        - assets/images/scenes/classroom/
        - assets/images/scenes/outside/
        - assets/images/scenes/corridor/
        - assets/images/scenes/second-corridor/
        - assets/images/scenes/stage/
        - assets/images/scenes/scene/
        - assets/images/wall-patterns/
        - assets/sounds/paths/
        - assets/sounds/survey/
        - assets/sounds/player-cards/
        - assets/sounds/items/
        - assets/sounds/tips/
        - assets/sounds/other/
