name: emvia
description: 'Emvia, a simple relaxing game to unwind and find your inner peace.'
publish_to: 'none'

version: 1.0.0+1

environment:
    sdk: ^3.10.7

dependencies:
    flutter:
        sdk: flutter

    flame: ^1.34.0
    flame_audio: ^2.11.12
    google_fonts: ^7.0.2
    cupertino_icons: ^1.0.8
    flutter_localizations:
        sdk: flutter
    intl: 0.20.2
    shared_preferences: ^2.5.4

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^6.0.0

flutter:
    generate: true
    uses-material-design: true

    assets:
        - assets/images/
        - assets/images/main-menu/
        - assets/images/overlays/
        - assets/images/player/
        - assets/images/player-selecting/
        - assets/images/scenes/
        - assets/images/scenes/classroom/
        - assets/images/scenes/corridor/